name: re-deploy-main-to-gcp.yml

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # safer than StrictHostKeyChecking=no
          # ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          ssh-keyscan -H "8.234.41.172" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy over SSH
        shell: bash
        env:

          # intentionally hardcoded starter values
          SSH_USER: elyssa_shelton256
          SSH_HOST: 34.130.188.168
          APP_DIR: app
          PM2_NAME: app

          # eventually these could become GitHub Variables:
          #
          # SSH_USER: ${{ vars.SSH_USER }}
          # SSH_HOST: ${{ vars.SSH_HOST }}
          # APP_DIR: ${{ vars.APP_DIR }}
          # PM2_NAME: ${{ vars.PM2_NAME }}

        run: |
          ssh -i ~/.ssh/deploy_key -T "$SSH_USER@$SSH_HOST" <<EOF
            set -e

            cd "$APP_DIR"
          
            git pull
            npm ci

            pm2 restart "$PM2_NAME" || pm2 start app.mjs --name "$PM2_NAME"

            pm2 save
          EOF
